# Generated by Django 5.2.17 on 2026-10-05 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caratteristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, unique=True)),
                ("descrizione", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "caratteristica macchina",
                "verbose_name_plural": "caratteristiche macchina",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ragione_sociale", models.CharField(max_length=200)),
                ("indirizzo", models.TextField(blank=True)),
                ("paese", models.CharField(blank=True, max_length=60)),
            ],
            options={
                "verbose_name_plural": "clienti",
                "ordering": ["ragione_sociale"],
            },
        ),
        migrations.CreateModel(
            name="CondizioneOperativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=60, unique=True)),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "condizione operativa",
                "verbose_name_plural": "condizioni operative",
                "ordering": ["ordine"],
            },
        ),
        migrations.CreateModel(
            name="Fabbricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ragione_sociale", models.CharField(max_length=200)),
                ("indirizzo", models.TextField()),
                (
                    "persona_fascicolo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="persona autorizzata a costituire il fascicolo tecnico",
                    ),
                ),
                ("indirizzo_persona_fascicolo", models.TextField(blank=True)),
                ("firmatario", models.CharField(blank=True, max_length=200)),
                ("qualifica_firmatario", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "dati del fabbricante",
                "verbose_name_plural": "dati del fabbricante",
            },
        ),
        migrations.CreateModel(
            name="MetodoStima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("versione", models.CharField(max_length=40, unique=True)),
                ("descrizione", models.TextField(blank=True)),
                (
                    "attivo",
                    models.BooleanField(
                        default=False, help_text="Metodo usato per le nuove revisioni."
                    ),
                ),
            ],
            options={
                "verbose_name": "metodo di stima",
                "verbose_name_plural": "metodi di stima",
            },
        ),
        migrations.CreateModel(
            name="Norma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=60, unique=True)),
                ("titolo", models.CharField(blank=True, max_length=300)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("A", "Tipo A"),
                            ("B", "Tipo B"),
                            ("C", "Tipo C"),
                            ("-", "Altro"),
                        ],
                        default="-",
                        max_length=1,
                    ),
                ),
                ("edizione_citata", models.CharField(blank=True, max_length=40)),
                ("edizione_vigente", models.CharField(blank=True, max_length=40)),
                (
                    "armonizzata",
                    models.BooleanField(
                        default=False,
                        help_text="Presente nell'elenco delle norme armonizzate per il Regolamento.",
                    ),
                ),
                ("nota", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "norme",
                "ordering": ["codice"],
            },
        ),
        migrations.CreateModel(
            name="Pericolo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        help_text="EN ISO 12100, allegato B.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("descrizione", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name_plural": "pericoli",
                "ordering": ["codice"],
            },
        ),
        migrations.CreateModel(
            name="RiferimentoNormativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=40, unique=True)),
                ("nome", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "riferimento normativo",
                "verbose_name_plural": "riferimenti normativi",
            },
        ),
        migrations.CreateModel(
            name="Commessa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, unique=True)),
                ("descrizione", models.CharField(blank=True, max_length=300)),
                ("anno", models.PositiveSmallIntegerField()),
                ("paese_destinazione", models.CharField(blank=True, max_length=60)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commesse",
                        to="rischi.cliente",
                    ),
                ),
                (
                    "riferimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rischi.riferimentonormativo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "commesse",
                "ordering": ["-anno", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="Macchina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denominazione", models.CharField(max_length=200)),
                ("modello", models.CharField(blank=True, max_length=100)),
                ("matricola", models.CharField(blank=True, max_length=60)),
                (
                    "anno_costruzione",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MACCHINA", "Macchina"),
                            ("INSIEME", "Insieme di macchine"),
                            ("QUASI", "Quasi-macchina"),
                        ],
                        default="MACCHINA",
                        max_length=10,
                    ),
                ),
                (
                    "materiali",
                    models.TextField(blank=True, verbose_name="materiali lavorati"),
                ),
                (
                    "caratteristiche",
                    models.ManyToManyField(
                        blank=True, related_name="macchine", to="rischi.caratteristica"
                    ),
                ),
                (
                    "commessa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="macchine",
                        to="rischi.commessa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "macchine",
            },
        ),
        migrations.CreateModel(
            name="Analisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("LIBRERIA", "Dai moduli della libreria"),
                            ("COPIA", "Copia di un'altra analisi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("creata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "macchina",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analisi",
                        to="rischi.macchina",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "analisi",
            },
        ),
        migrations.CreateModel(
            name="FasciaClasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cl_min", models.PositiveSmallIntegerField()),
                ("cl_max", models.PositiveSmallIntegerField()),
                (
                    "metodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fasce",
                        to="rischi.metodostima",
                    ),
                ),
            ],
            options={
                "verbose_name": "fascia di classe",
                "verbose_name_plural": "fasce di classe",
                "ordering": ["metodo", "cl_min"],
            },
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, unique=True)),
                ("descrizione", models.TextField(blank=True)),
                ("sempre_attivo", models.BooleanField(default=False)),
                ("attivo", models.BooleanField(default=True)),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
                (
                    "caratteristiche",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Il modulo si attiva se la macchina ha almeno una di queste caratteristiche.",
                        related_name="moduli",
                        to="rischi.caratteristica",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "moduli",
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.CreateModel(
            name="RegistroModifica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quando", models.DateTimeField(auto_now_add=True)),
                (
                    "azione",
                    models.CharField(
                        choices=[
                            ("CREA", "Creazione"),
                            ("MODIFICA", "Modifica"),
                            ("ELIMINA", "Eliminazione"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tabella", models.CharField(max_length=60)),
                ("oggetto_id", models.CharField(max_length=40)),
                ("descrizione", models.CharField(max_length=300)),
                (
                    "modifiche",
                    models.JSONField(default=dict, help_text="Campo: [prima, dopo]."),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "modifica registrata",
                "verbose_name_plural": "registro modifiche",
                "ordering": ["-quando"],
            },
        ),
        migrations.CreateModel(
            name="Revisione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("motivo", models.TextField(blank=True)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("BOZZA", "Bozza"),
                            ("IN_VERIFICA", "In verifica"),
                            ("APPROVATA", "Approvata"),
                            ("SOSTITUITA", "Sostituita"),
                        ],
                        default="BOZZA",
                        max_length=12,
                    ),
                ),
                ("creata_il", models.DateTimeField(auto_now_add=True)),
                ("inviata_il", models.DateTimeField(blank=True, null=True)),
                ("verificata_il", models.DateTimeField(blank=True, null=True)),
                ("approvata_il", models.DateTimeField(blank=True, null=True)),
                ("nota_verifica", models.TextField(blank=True)),
                (
                    "analisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisioni",
                        to="rischi.analisi",
                    ),
                ),
                (
                    "approvata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compilata_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "metodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rischi.metodostima",
                    ),
                ),
                (
                    "verificata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "revisioni",
                "ordering": ["analisi", "-numero"],
                "unique_together": {("analisi", "numero")},
            },
        ),
        migrations.CreateModel(
            name="DocumentoGenerato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VALUTAZIONE", "Valutazione dei rischi"),
                            ("RESIDUI", "Elenco dei rischi residui"),
                            ("DICHIARAZIONE", "Dichiarazione UE di conformità"),
                        ],
                        max_length=15,
                    ),
                ),
                ("file", models.FileField(upload_to="documenti/%Y/")),
                ("generato_il", models.DateTimeField(auto_now_add=True)),
                (
                    "generato_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documenti",
                        to="rischi.revisione",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento generato",
                "verbose_name_plural": "documenti generati",
                "ordering": ["-generato_il"],
            },
        ),
        migrations.AddField(
            model_name="analisi",
            name="copiata_da",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="rischi.revisione",
            ),
        ),
        migrations.CreateModel(
            name="RequisitoRESS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        help_text="Punto dell'Allegato III del Regolamento.",
                        max_length=20,
                    ),
                ),
                ("titolo", models.CharField(max_length=200)),
                (
                    "codice_direttiva",
                    models.CharField(
                        blank=True,
                        help_text="Punto dell'Allegato I della Direttiva 2006/42/CE.",
                        max_length=20,
                    ),
                ),
                (
                    "nuovo",
                    models.BooleanField(
                        default=False, help_text="Requisito introdotto dal Regolamento."
                    ),
                ),
                (
                    "novita",
                    models.TextField(blank=True, verbose_name="novità del Regolamento"),
                ),
                (
                    "azione",
                    models.TextField(blank=True, verbose_name="azione per la libreria"),
                ),
                ("ordine", models.PositiveIntegerField(default=0)),
                (
                    "riferimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rischi.riferimentonormativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "requisito RESS",
                "verbose_name_plural": "requisiti RESS",
                "ordering": ["riferimento", "ordine"],
                "unique_together": {("riferimento", "codice")},
            },
        ),
        migrations.CreateModel(
            name="ScalaFattore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fattore",
                    models.CharField(
                        choices=[
                            ("Se", "Se – Gravità"),
                            ("Fr", "Fr – Frequenza di esposizione"),
                            ("Pr", "Pr – Probabilità dell'evento"),
                            ("Av", "Av – Possibilità di evitare il danno"),
                        ],
                        max_length=2,
                    ),
                ),
                ("valore", models.PositiveSmallIntegerField()),
                ("descrizione", models.CharField(max_length=200)),
                (
                    "metodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scale",
                        to="rischi.metodostima",
                    ),
                ),
            ],
            options={
                "verbose_name": "valore di scala",
                "verbose_name_plural": "scale dei fattori",
                "ordering": ["metodo", "fattore", "-valore"],
            },
        ),
        migrations.CreateModel(
            name="SchedaAnalisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zona_impianto", models.CharField(blank=True, max_length=60)),
                ("zona_pericolosa", models.TextField(blank=True)),
                (
                    "se_iniziale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Se iniziale"
                    ),
                ),
                (
                    "fr_iniziale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Fr iniziale"
                    ),
                ),
                (
                    "pr_iniziale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pr iniziale"
                    ),
                ),
                (
                    "av_iniziale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Av iniziale"
                    ),
                ),
                (
                    "se_finale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Se finale"
                    ),
                ),
                (
                    "fr_finale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Fr finale"
                    ),
                ),
                (
                    "pr_finale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pr finale"
                    ),
                ),
                (
                    "av_finale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Av finale"
                    ),
                ),
                (
                    "testo_istruzioni",
                    models.TextField(
                        blank=True,
                        verbose_name="indicazioni per le istruzioni / rischio residuo",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("codice", models.CharField(blank=True, max_length=20)),
                (
                    "decisione",
                    models.CharField(
                        choices=[
                            ("PROPOSTA", "Da decidere"),
                            ("CONFERMATA", "Confermata"),
                            ("MODIFICATA", "Modificata"),
                            ("SCARTATA", "Scartata"),
                            ("AGGIUNTA", "Aggiunta a mano"),
                        ],
                        default="PROPOSTA",
                        max_length=10,
                    ),
                ),
                ("motivazione", models.TextField(blank=True)),
                ("decisa_il", models.DateTimeField(blank=True, null=True)),
                (
                    "condizioni",
                    models.ManyToManyField(blank=True, to="rischi.condizioneoperativa"),
                ),
                (
                    "decisa_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rischi.modulo"
                    ),
                ),
                ("norme", models.ManyToManyField(blank=True, to="rischi.norma")),
                ("pericoli", models.ManyToManyField(blank=True, to="rischi.pericolo")),
                (
                    "requisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rischi.requisitoress",
                    ),
                ),
                (
                    "revisione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schede",
                        to="rischi.revisione",
                    ),
                ),
            ],
            options={
                "verbose_name": "scheda dell'analisi",
                "verbose_name_plural": "schede dell'analisi",
                "ordering": ["modulo__ordine", "requisito__ordine", "codice"],
            },
        ),
        migrations.CreateModel(
            name="MisuraAnalisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PROG", "Progettazione intrinsecamente sicura"),
                            ("PROT", "Protezione e misure complementari"),
                            ("INFO", "Informazioni per l'uso"),
                            ("DACL", "Da classificare"),
                        ],
                        default="DACL",
                        max_length=4,
                    ),
                ),
                ("testo", models.TextField()),
                (
                    "norma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rischi.norma",
                    ),
                ),
                (
                    "scheda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misure",
                        to="rischi.schedaanalisi",
                    ),
                ),
            ],
            options={
                "verbose_name": "misura",
                "verbose_name_plural": "misure di protezione",
                "ordering": ["ordine", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SchedaModello",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zona_impianto", models.CharField(blank=True, max_length=60)),
                ("zona_pericolosa", models.TextField(blank=True)),
                (
                    "se_iniziale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Se iniziale"
                    ),
                ),
                (
                    "fr_iniziale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Fr iniziale"
                    ),
                ),
                (
                    "pr_iniziale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pr iniziale"
                    ),
                ),
                (
                    "av_iniziale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Av iniziale"
                    ),
                ),
                (
                    "se_finale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Se finale"
                    ),
                ),
                (
                    "fr_finale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Fr finale"
                    ),
                ),
                (
                    "pr_finale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pr finale"
                    ),
                ),
                (
                    "av_finale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Av finale"
                    ),
                ),
                (
                    "testo_istruzioni",
                    models.TextField(
                        blank=True,
                        verbose_name="indicazioni per le istruzioni / rischio residuo",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("codice", models.CharField(max_length=20, unique=True)),
                (
                    "scheda_originale",
                    models.CharField(
                        blank=True,
                        help_text="Riferimento alla valutazione di origine.",
                        max_length=40,
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[("BOZZA", "Bozza"), ("VALIDATA", "Validata")],
                        default="BOZZA",
                        max_length=10,
                    ),
                ),
                (
                    "condizioni",
                    models.ManyToManyField(blank=True, to="rischi.condizioneoperativa"),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schede",
                        to="rischi.modulo",
                    ),
                ),
                ("norme", models.ManyToManyField(blank=True, to="rischi.norma")),
                ("pericoli", models.ManyToManyField(blank=True, to="rischi.pericolo")),
                (
                    "requisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schede_modello",
                        to="rischi.requisitoress",
                    ),
                ),
            ],
            options={
                "verbose_name": "scheda modello",
                "verbose_name_plural": "schede modello",
                "ordering": ["codice"],
            },
        ),
        migrations.AddField(
            model_name="schedaanalisi",
            name="origine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="rischi.schedamodello",
            ),
        ),
        migrations.CreateModel(
            name="MisuraModello",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PROG", "Progettazione intrinsecamente sicura"),
                            ("PROT", "Protezione e misure complementari"),
                            ("INFO", "Informazioni per l'uso"),
                            ("DACL", "Da classificare"),
                        ],
                        default="DACL",
                        max_length=4,
                    ),
                ),
                ("testo", models.TextField()),
                (
                    "norma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rischi.norma",
                    ),
                ),
                (
                    "scheda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misure",
                        to="rischi.schedamodello",
                    ),
                ),
            ],
            options={
                "verbose_name": "misura",
                "verbose_name_plural": "misure di protezione",
                "ordering": ["ordine", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CellaMatrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("se", models.PositiveSmallIntegerField()),
                (
                    "esito",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("SUGGERITE", "Misure suggerite"),
                            ("RICHIESTE", "Misure richieste"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fascia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rischi.fasciaclasse",
                    ),
                ),
                (
                    "metodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="celle",
                        to="rischi.metodostima",
                    ),
                ),
            ],
            options={
                "verbose_name": "cella della matrice",
                "verbose_name_plural": "matrice",
                "ordering": ["metodo", "-se", "fascia__cl_min"],
                "unique_together": {("metodo", "se", "fascia")},
            },
        ),
        migrations.CreateModel(
            name="ApplicabilitaRequisito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicabile", models.BooleanField(default=True)),
                ("motivazione", models.TextField(blank=True)),
                (
                    "requisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rischi.requisitoress",
                    ),
                ),
                (
                    "revisione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicabilita",
                        to="rischi.revisione",
                    ),
                ),
            ],
            options={
                "verbose_name": "applicabilità requisito",
                "verbose_name_plural": "applicabilità requisiti",
                "ordering": ["requisito__ordine"],
                "unique_together": {("revisione", "requisito")},
            },
        ),
    ]
