# Generated by Django 5.2.17 on 2026-10-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegislazioneUE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        help_text="Es. 2014/30/UE", max_length=40, unique=True
                    ),
                ),
                ("titolo", models.CharField(max_length=300)),
                (
                    "titolo_en",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="titolo in inglese"
                    ),
                ),
                (
                    "predefinita",
                    models.BooleanField(
                        default=False, help_text="Proposta per le nuove macchine."
                    ),
                ),
            ],
            options={
                "verbose_name": "legislazione UE",
                "verbose_name_plural": "legislazioni UE",
                "ordering": ["codice"],
            },
        ),
        migrations.AddField(
            model_name="documentogenerato",
            name="definitivo",
            field=models.BooleanField(
                default=False, help_text="Generato da una revisione approvata."
            ),
        ),
        migrations.AddField(
            model_name="documentogenerato",
            name="lingua",
            field=models.CharField(default="it", max_length=2),
        ),
        migrations.AddField(
            model_name="fabbricante",
            name="luogo",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="luogo di emissione delle dichiarazioni",
            ),
        ),
        migrations.AddField(
            model_name="fabbricante",
            name="partita_iva",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="partita IVA"
            ),
        ),
        migrations.AddField(
            model_name="macchina",
            name="funzione",
            field=models.TextField(
                blank=True,
                help_text="Denominazione generica e funzione, come compare nella dichiarazione.",
            ),
        ),
        migrations.AddField(
            model_name="macchina",
            name="organismo_notificato",
            field=models.TextField(
                blank=True,
                help_text="Solo per le macchine dell'Allegato I del Regolamento: nome, numero, procedura e certificato.",
            ),
        ),
        migrations.AddField(
            model_name="macchina",
            name="altre_legislazioni",
            field=models.ManyToManyField(
                blank=True,
                help_text="Oltre al Regolamento (UE) 2023/1230.",
                to="rischi.legislazioneue",
            ),
        ),
    ]
