# Generated by Django 5.2.17 on 2026-10-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rischi', '0005_senza_caratteristiche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('OPERATORE', 'Operatore (RESS 1.1.1 d)'), ('ESPOSTA', 'Persona esposta (RESS 1.1.1 c)')], default='OPERATORE', max_length=10)),
                ('descrizione', models.TextField(blank=True, help_text='Descrizione standard, proposta nelle nuove commesse.')),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'figura',
                'verbose_name_plural': 'figure (soggetti esposti)',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='schedaanalisi',
            name='soggetti',
            field=models.ManyToManyField(blank=True, to='rischi.figura', verbose_name='soggetti esposti'),
        ),
        migrations.AddField(
            model_name='schedamodello',
            name='soggetti',
            field=models.ManyToManyField(blank=True, to='rischi.figura', verbose_name='soggetti esposti'),
        ),
        migrations.CreateModel(
            name='FiguraMacchina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True, help_text='Es. "Mulettista che transita nella corsia adiacente".')),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rischi.figura')),
                ('macchina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure', to='rischi.macchina')),
            ],
            options={
                'verbose_name': 'figura della macchina',
                'verbose_name_plural': 'figure della macchina',
                'ordering': ['figura__ordine', 'figura__nome'],
                'unique_together': {('macchina', 'figura')},
            },
        ),
    ]
