# Generated by Django 5.2.17 on 2026-10-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rischi', '0007_figure_iniziali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedaanalisi',
            name='pericoli',
            field=models.ManyToManyField(blank=True, to='rischi.pericolo', verbose_name='pericoli (RESS 1.1.1 a)'),
        ),
        migrations.AlterField(
            model_name='schedaanalisi',
            name='soggetti',
            field=models.ManyToManyField(blank=True, to='rischi.figura', verbose_name='soggetti esposti (RESS 1.1.1 c, d)'),
        ),
        migrations.AlterField(
            model_name='schedaanalisi',
            name='zona_pericolosa',
            field=models.TextField(blank=True, verbose_name='zona pericolosa (RESS 1.1.1 b)'),
        ),
        migrations.AlterField(
            model_name='schedamodello',
            name='pericoli',
            field=models.ManyToManyField(blank=True, to='rischi.pericolo', verbose_name='pericoli (RESS 1.1.1 a)'),
        ),
        migrations.AlterField(
            model_name='schedamodello',
            name='soggetti',
            field=models.ManyToManyField(blank=True, to='rischi.figura', verbose_name='soggetti esposti (RESS 1.1.1 c, d)'),
        ),
        migrations.AlterField(
            model_name='schedamodello',
            name='zona_pericolosa',
            field=models.TextField(blank=True, verbose_name='zona pericolosa (RESS 1.1.1 b)'),
        ),
    ]
