# Generated by Django 5.2.17 on 2026-10-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rischi', '0008_etichette_ress_1_1_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='sigla',
            field=models.CharField(blank=True, help_text='Lettere iniziali dei codici delle schede del modulo, es. GEN per GEN-01, GEN-02…', max_length=6),
        ),
    ]
