# Generated by Django 5.2.17 on 2026-10-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rischi', '0011_codici_con_ress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedamodello',
            name='codice',
            field=models.CharField(help_text='Si genera da solo: sigla del modulo, punto RESS e indice (es. TAV-1.3.8.2-1).', max_length=20, unique=True),
        ),
    ]
