# Generated by Django 5.2.17 on 2026-10-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0014_pericoli_iso12100"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedaanalisi",
            name="considerazioni_limiti",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sui limiti"
            ),
        ),
        migrations.AddField(
            model_name="schedaanalisi",
            name="considerazioni_pericoli",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sui pericoli"
            ),
        ),
        migrations.AddField(
            model_name="schedaanalisi",
            name="considerazioni_riduzione",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sulla riduzione del rischio"
            ),
        ),
        migrations.AddField(
            model_name="schedaanalisi",
            name="considerazioni_soggetti",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sui soggetti esposti"
            ),
        ),
        migrations.AddField(
            model_name="schedaanalisi",
            name="considerazioni_stima_finale",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sulla stima finale"
            ),
        ),
        migrations.AddField(
            model_name="schedaanalisi",
            name="considerazioni_stima_iniziale",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sulla stima iniziale"
            ),
        ),
        migrations.AddField(
            model_name="schedamodello",
            name="considerazioni_limiti",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sui limiti"
            ),
        ),
        migrations.AddField(
            model_name="schedamodello",
            name="considerazioni_pericoli",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sui pericoli"
            ),
        ),
        migrations.AddField(
            model_name="schedamodello",
            name="considerazioni_riduzione",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sulla riduzione del rischio"
            ),
        ),
        migrations.AddField(
            model_name="schedamodello",
            name="considerazioni_soggetti",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sui soggetti esposti"
            ),
        ),
        migrations.AddField(
            model_name="schedamodello",
            name="considerazioni_stima_finale",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sulla stima finale"
            ),
        ),
        migrations.AddField(
            model_name="schedamodello",
            name="considerazioni_stima_iniziale",
            field=models.TextField(
                blank=True, verbose_name="considerazioni sulla stima iniziale"
            ),
        ),
        migrations.AlterField(
            model_name="schedaanalisi",
            name="note",
            field=models.TextField(
                blank=True, verbose_name="note e considerazioni generali"
            ),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="note",
            field=models.TextField(
                blank=True, verbose_name="note e considerazioni generali"
            ),
        ),
    ]
