# Generated by Django 5.2.17 on 2026-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0015_considerazioni_per_sezione"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedaanalisi",
            name="pericoli",
            field=models.ManyToManyField(
                blank=True, to="rischi.pericolo", verbose_name="pericoli"
            ),
        ),
        migrations.AlterField(
            model_name="schedaanalisi",
            name="soggetti",
            field=models.ManyToManyField(
                blank=True, to="rischi.figura", verbose_name="soggetti esposti"
            ),
        ),
        migrations.AlterField(
            model_name="schedaanalisi",
            name="zona_pericolosa",
            field=models.TextField(blank=True, verbose_name="zona pericolosa"),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="pericoli",
            field=models.ManyToManyField(
                blank=True, to="rischi.pericolo", verbose_name="pericoli"
            ),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="soggetti",
            field=models.ManyToManyField(
                blank=True, to="rischi.figura", verbose_name="soggetti esposti"
            ),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="zona_pericolosa",
            field=models.TextField(blank=True, verbose_name="zona pericolosa"),
        ),
    ]
