# Generated by Django 5.2.17 on 2026-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0016_etichette_senza_ress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedaanalisi",
            name="considerazioni_limiti",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedaanalisi",
            name="considerazioni_pericoli",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedaanalisi",
            name="considerazioni_riduzione",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedaanalisi",
            name="considerazioni_soggetti",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedaanalisi",
            name="considerazioni_stima_finale",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedaanalisi",
            name="considerazioni_stima_iniziale",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="considerazioni_limiti",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="considerazioni_pericoli",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="considerazioni_riduzione",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="considerazioni_soggetti",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="considerazioni_stima_finale",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
        migrations.AlterField(
            model_name="schedamodello",
            name="considerazioni_stima_iniziale",
            field=models.TextField(blank=True, verbose_name="considerazioni"),
        ),
    ]
