# Generated by Django 5.2.17 on 2026-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0017_considerazioni_etichetta"),
    ]

    operations = [
        migrations.AddField(
            model_name="macchina",
            name="schede_escluse",
            field=models.ManyToManyField(
                blank=True,
                help_text="Schede modello dei moduli attivati che non entrano nell'analisi di questa macchina.",
                related_name="macchine_escluse",
                to="rischi.schedamodello",
            ),
        ),
    ]
