# Generated by Django 5.2.17 on 2026-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0018_schede_escluse"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabbricante",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo stampato sulla pagina di intestazione della valutazione dei rischi (PNG o JPG).",
                upload_to="logo/",
            ),
        ),
    ]
