# Generated by Django 5.2.17 on 2026-10-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0021_requisiti_allegato_iii"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedaanalisi",
            name="stampa_note_requisito",
            field=models.BooleanField(
                default=False,
                help_text="Nella valutazione dei rischi riporta il testo del requisito RESS (Allegato III del Regolamento).",
                verbose_name="stampa le note del requisito nel PDF",
            ),
        ),
        migrations.AddField(
            model_name="schedamodello",
            name="stampa_note_requisito",
            field=models.BooleanField(
                default=False,
                help_text="Nella valutazione dei rischi riporta il testo del requisito RESS (Allegato III del Regolamento).",
                verbose_name="stampa le note del requisito nel PDF",
            ),
        ),
    ]
