# Generated by Django 5.2.17 on 2026-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0022_stampa_note_requisito"),
    ]

    operations = [
        migrations.AddField(
            model_name="macchina",
            name="requisiti_esclusi",
            field=models.ManyToManyField(
                blank=True,
                help_text="Requisiti RESS non considerati per questa macchina: le loro schede non entrano nell'analisi.",
                related_name="macchine_escluse",
                to="rischi.requisitoress",
            ),
        ),
        migrations.AddField(
            model_name="pericolo",
            name="norme",
            field=models.ManyToManyField(
                blank=True,
                help_text="Norme di riferimento: nel PDF compaiono tra le norme delle schede che analizzano il pericolo.",
                related_name="pericoli",
                to="rischi.norma",
            ),
        ),
    ]
