# Generated by Django 5.2.17 on 2026-10-08 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0023_requisiti_esclusi_norme_pericoli"),
    ]

    operations = [
        migrations.AddField(
            model_name="macchina",
            name="norme_tipo_c",
            field=models.ManyToManyField(
                blank=True,
                help_text="Norme di prodotto della macchina (es. EN ISO 16089 per le rettificatrici fisse): valgono per tutta l'analisi ed entrano nella dichiarazione.",
                limit_choices_to={"tipo": "C"},
                related_name="macchine",
                to="rischi.norma",
                verbose_name="norme di tipo C",
            ),
        ),
        migrations.AddField(
            model_name="norma",
            name="sempre_applicata",
            field=models.BooleanField(
                default=False,
                help_text="Entra in tutte le analisi senza doverla scegliere (es. EN ISO 12100): dichiarazione e valutazione.",
            ),
        ),
        migrations.CreateModel(
            name="SoluzioneProtezione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PROG", "Progettazione intrinsecamente sicura"),
                            ("PROT", "Protezione e misure complementari"),
                            ("INFO", "Informazioni per l'uso"),
                            ("DACL", "Da classificare"),
                        ],
                        default="PROT",
                        max_length=4,
                    ),
                ),
                (
                    "testo",
                    models.TextField(
                        blank=True,
                        help_text="Si precompila nella misura quando si sceglie la soluzione.",
                        verbose_name="testo proposto",
                    ),
                ),
                (
                    "norme",
                    models.ManyToManyField(
                        blank=True, related_name="soluzioni", to="rischi.norma"
                    ),
                ),
            ],
            options={
                "verbose_name": "soluzione di protezione",
                "verbose_name_plural": "soluzioni di protezione",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="misuraanalisi",
            name="soluzione",
            field=models.ForeignKey(
                blank=True,
                help_text="Le norme della soluzione entrano nell'area Norme della scheda.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="misure_analisi",
                to="rischi.soluzioneprotezione",
            ),
        ),
        migrations.AddField(
            model_name="misuramodello",
            name="soluzione",
            field=models.ForeignKey(
                blank=True,
                help_text="Le norme della soluzione entrano nell'area Norme della scheda.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="misure_modello",
                to="rischi.soluzioneprotezione",
            ),
        ),
    ]
