# Generated by Django 5.2.17 on 2026-10-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0025_catalogo_soluzioni"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisitoress",
            name="norme",
            field=models.ManyToManyField(
                blank=True,
                help_text="Norme tipiche del requisito: entrano da sole nell'area Norme delle schede del requisito.",
                related_name="requisiti",
                to="rischi.norma",
            ),
        ),
        migrations.AddField(
            model_name="schedaanalisi",
            name="norme_escluse",
            field=models.ManyToManyField(
                blank=True,
                help_text="Norme ricavate in automatico che non riguardano questa scheda.",
                related_name="schede_escluse",
                to="rischi.norma",
            ),
        ),
        migrations.AddField(
            model_name="schedamodello",
            name="norme_escluse",
            field=models.ManyToManyField(
                blank=True,
                help_text="Norme ricavate in automatico che non riguardano questa scheda.",
                related_name="schede_modello_escluse",
                to="rischi.norma",
            ),
        ),
        migrations.AddField(
            model_name="soluzioneprotezione",
            name="parole_chiave",
            field=models.TextField(
                blank=True,
                help_text="Separate da virgola. Se il testo di una misura senza soluzione ne contiene una, la misura è riconosciuta come questa soluzione e ne prende le norme (es. interblocc, porte interbloccate).",
                verbose_name="parole chiave",
            ),
        ),
    ]
