# Generated by Django 5.2.17 on 2026-10-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0028_sintesi_norme"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitoloValutazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=150)),
                ("testo", models.TextField(blank=True)),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
                (
                    "attivo",
                    models.BooleanField(default=True, verbose_name="stampa nel PDF"),
                ),
            ],
            options={
                "verbose_name": "capitolo della valutazione",
                "verbose_name_plural": "capitoli della valutazione",
                "ordering": ["ordine", "pk"],
            },
        ),
    ]
