# Generated by Django 5.2.17 on 2026-10-09 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rischi", "0030_capitoli_iniziali"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllegatoAnalisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Immagine (JPG, PNG, GIF, BMP) o PDF.",
                        upload_to="allegati/%Y/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "gif", "bmp", "pdf"]
                            )
                        ],
                    ),
                ),
                ("didascalia", models.CharField(blank=True, max_length=200)),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
                (
                    "scheda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allegati",
                        to="rischi.schedaanalisi",
                    ),
                ),
            ],
            options={
                "verbose_name": "immagine allegata",
                "verbose_name_plural": "immagini allegate",
                "ordering": ["ordine", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AllegatoModello",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Immagine (JPG, PNG, GIF, BMP) o PDF.",
                        upload_to="allegati/%Y/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "gif", "bmp", "pdf"]
                            )
                        ],
                    ),
                ),
                ("didascalia", models.CharField(blank=True, max_length=200)),
                ("ordine", models.PositiveSmallIntegerField(default=0)),
                (
                    "scheda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allegati",
                        to="rischi.schedamodello",
                    ),
                ),
            ],
            options={
                "verbose_name": "immagine allegata",
                "verbose_name_plural": "immagini allegate",
                "ordering": ["ordine", "pk"],
                "abstract": False,
            },
        ),
    ]
